sudo: required

env:
    global:
        - PACKAGE="DiffView"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

env:
    global:
        - PACKAGE="DiffView"
        - SUBLIME_TEXT_VERSION="3"

matrix:
    include:
        - os: linux
          language: python
        - os: osx
          language: generic


before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap

script:
    # run tests with test coverage report
    - sh travis.sh run_tests --coverage

after_success:
    # remove the following if `coveralls` is not needed
    - pip3 install python-coveralls;
    - pip3 install codecov;
    - coveralls
    - codecov

notifications:
    email: false
